---
abstract: 'A perl PagerDuty client'
author:
  - 'Matt Harrington'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  HTTP::Response: '0'
  IO::Uncompress::Gunzip: '0'
  Test::CPAN::Changes::ReallyStrict: '0'
  Test::LWP::UserAgent: '0'
  Test::More: '0.88'
  Test::Perl::Critic: '1.03'
  Test::Warn: '0.30'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PagerDuty-Agent
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dump: '0'
  English: '0'
  HTTP::Request::Common: '0'
  JSON: '0'
  LWP::Protocol::https: '0'
  LWP::UserAgent: '0'
  Moo: '0'
  MooX::Types::MooseLike::Base: '0'
  Sys::Hostname: '0'
  Time::Piece: '0'
  perl: '5.010'
resources:
  repository: https://github.com/querry43/perl-pagerduty-agent
version: 0.02c
x_homepage: https://github.com/querry43/perl-pagerduty-agent
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
